meta:
  url: https://github.com/alisyahidin
  title: Intro to web component
  description: Presentation deck intro about web component
  siteName: github.com
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: bullets
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: tomorrow # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
extends:
  css: style.css