meta:
  title: Intro to web component
  description: Presentation deck intro about web component
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: bullets
  code:
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
    languages:
      - javascript
      - html
extends:
  css: style.css
  js: index.js